name: Metrics
on:
  # Roda todos os dias à meia-noite UTC
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token de Acesso configurado nos Secrets do repositório
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Configurações do Perfil
          user: artrosisca
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Plugins Ativos
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
